### ISSUE TITLE
Expressing complex batches

### ISSUE THREAD

**Issue by metaphori** [AlchemistSimulator/Alchemist#697]
Assume you have 3 vars `A (5) ,B (3), C (2)` where the numbers within parentheses express the num of values you want them to range over. Sometimes, running `5*3*2=30` simulations may be a overhead (e.g., in terms of time), so you may want to do the following trick: *let each variable vary while taking the other variables fixed (i.e., by using one value as their default value)*. In that case, you'll have `5+3+2 = 10` runs, or, actually `1+4+2+1=8` (since you have one execution with all defaults, and then you do not need each variable to vary with their default value, only its remaining ones).

**Comment by DanySK** [comment]
You can already achieve something like that by exploiting support for arbitrarily defined variables on Alchemist 10+: look at https://github.com/DanySK/Experiment-2020-LMCS-TimeFluid/blob/109b6b1e0c740209effe79c42dac520f67cf1f1e/src/main/yaml/gradient.yml#L20-L21

You could define a `List[Tuple2[V, ListV]]` (I'm using a Scala-like syntax [just because](https://user-images.githubusercontent.com/1991673/105471379-f4fef280-5c9a-11eb-99e4-c27667fc448f.png), but you can use Groovy or whatever), where the first element of the tuple is the default value, then create a single independent variable that runs from 0 to to the sum of the lengths of the inner lists, and get the values you need as the value "pointed" by this variable for the variable under test, and the default for the others.

However this is tricky and uncomfortable and we should keep this open to work on a better matrix expansion system (with filters and so on).

**Comment by DanySK** [comment]
Custom matrix expansion can now be realized via custom `Launcher`s.
